import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import Avatar from "../public/Avatar.png";
import BCT from "../public/BCT.jpg";
import LLM from "../public/LLM.jpg";
import TODO from "../public/Todo-app.jpg";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bernardin Milhet Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="flex justify-between py-10 mb-12 dark:text-white">
            <h1 className="text-3xl font-semibold font-DancingS">BM</h1>
            <ul className="flex items-center ">
              <li>
                <a
                  className="px-4 py-2 ml-8 text-white rounded-md bg-gradient-to-r from-cyan-500 to-teal-500"
                  href="#competences"
                >
                  Compétences
                </a>
              </li>
              <li>
                <a
                  className="px-4 py-2 ml-8 text-white rounded-md bg-gradient-to-r from-cyan-500 to-teal-500"
                  href="#resume"
                >
                  A propos
                </a>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="ml-8 text-2xl cursor-pointer" />
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center">
            <h2 className="py-2 text-5xl font-semibold text-or font-DancingS dark:text-teal-400 md:text-6xl">
              Bernardin Milhet
            </h2>
            <h3 className="py-2 text-2xl dark:text-white md:text-3xl">Développeur Web et Web Mobile.</h3>

          </div>
          <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-300">
            <a href="mailto:bernardin2608@gmail.com" aria-label="adresse email"><AiFillMail /></a>
            <a href="https://www.linkedin.com/in/bernardin-milhet-a590b1149/" aria-label="lien linkedin"><AiFillLinkedin /></a>
            <a href="https://github.com/Kelhann2608/" aria-label="lien linkedin"><AiFillGithub /></a>
          </div>

          <div className="relative mx-auto mt-20 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 w-80 h-80 md:h-96 md:w-96">
            <Image src={Avatar} layout="fill" objectFit="cover" />
          </div>
          <div>
            <h3 id="resume" className="py-1 mt-2 mb-2 text-3xl text-center dark:text-white">A propos de moi :</h3>
            <p className="max-w-xl py-5 mx-auto leading-8 text-gray-800 text-md dark:text-gray-200 md:text-xl">
              Fan de technologies depuis mon plus jeune âge, j'avais pour habitude
              de démonter différents objets pour comprendre leur fonctionnement, à
              l'âge adulte, j'ai décidé de faire de même avec des ordinateurs. Puis,
              j'ai voulu comprendre leur langage, c'est ce qui m'a décidé à me
              diriger vers le monde du code et de la programmation. J'ai donc pris
              la décision de me lancer dans une formation de Développeur Web auprès
              de la Wild Code School, que je viens de terminer.Je suis donc à la recherche d'une opportunité pour mettre en pratique mes compétences.
            </p>
          </div>
          <div>
            <h3 id="competences" className="py-1 mt-2 mb-2 text-3xl text-center dark:text-white">Compétences :</h3>
            <p className="max-w-xl py-5 mx-auto leading-8 text-or text-md dark:text-teal-400 md:text-xl">
              HTML, CSS, JavaScript, React Js, Sass, Node Js, Astro Js, tailwind
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-white">Mes services :</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">Je propose mes services pour la création de sites web, tels que:  <br /><span className="text-lg font-semibold text-or dark:text-teal-400">Portfolio, site d'association, blogs, site vitrine</span> .</p>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Projets</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
              Vous pourrez trouver ci-dessous quelques uns des projets auxquels j'ai participé ou que j'ai conçu moi-même.
            </p>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="relative flex-1 basis-1/3">
              <Image
                className="object-cover rounded-lg "
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={BCT}
              />
              {/* <a className="absolute text-white border-2 border-black rounded-md bg-gradient-to-r from-cyan-500 to-teal-500 bottom-4 left-60" href="https://marie5060.github.io/Blind-Crash-Test/">Lien du site</a> */}

            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="object-cover rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={LLM}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="object-cover rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={TODO}
              />
            </div>
            {/* <div className="flex-1 basis-1/3">
              <Image
                className="object-cover rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div> */}


          </div>
        </section>
      </main>
    </div >
  );
}
